services:
  php:
    build: .
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: limesurvey
    ports:
      - "3306:3306"
    volumes:
      - ./db/limesurvey.sql:/docker-entrypoint-initdb.d/limesurvey.sql